/**
 * Vocabulary seed data for the in-memory WordStore.
 * Extracted from word_store.js for maintainability.
 */

export function seedWords() {
  const now = new Date().toISOString();
  return [
    // ── English words ────────────────────────────────────────────────────────
    {
      id: 'word_reliable',
      term: 'reliable',
      language: 'en',
      meaning_vi: 'đáng tin cậy',
      part_of_speech: 'adjective',
      ipa: '/rɪˈlaɪəbl/',
      vietnamese_pronunciation: 'ri-lai-uh-bol',
      example: 'She is a reliable teammate.',
      example_vi: 'Cô ấy là một đồng đội đáng tin cậy.',
      difficulty: 'B1',
      topics: ['work', 'people'],
      entry_type: 'word',
      explanation: '',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'word_adjust',
      term: 'adjust',
      language: 'en',
      meaning_vi: 'điều chỉnh',
      part_of_speech: 'verb',
      ipa: '/əˈdʒʌst/',
      vietnamese_pronunciation: 'uh-just',
      example: 'Please adjust the schedule.',
      example_vi: 'Vui lòng điều chỉnh lịch trình.',
      difficulty: 'B1',
      topics: ['work', 'daily'],
      entry_type: 'word',
      explanation: '',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    // ── English phrases ──────────────────────────────────────────────────────
    {
      id: 'phrase_break_the_ice',
      term: 'break the ice',
      language: 'en',
      meaning_vi: 'phá vỡ sự im lặng, tạo không khí thoải mái ban đầu',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'He told a joke to break the ice at the meeting.',
      example_vi: 'Anh ấy kể một câu chuyện cười để phá vỡ bầu không khí ngại ngùng trong cuộc họp.',
      difficulty: 'B2',
      topics: ['social', 'communication'],
      entry_type: 'phrase',
      explanation:
        'Dùng khi muốn tạo không khí thoải mái ở đầu buổi gặp mặt hoặc khi mọi người chưa quen nhau. Thường dùng trong ngữ cảnh xã hội hoặc công việc.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_under_the_weather',
      term: 'under the weather',
      language: 'en',
      meaning_vi: 'cảm thấy không khỏe, hơi ốm',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "I can't come to work today — I'm feeling a bit under the weather.",
      example_vi: 'Tôi không thể đến làm hôm nay — tôi cảm thấy hơi không khỏe.',
      difficulty: 'B1',
      topics: ['health', 'daily'],
      entry_type: 'phrase',
      explanation:
        'Dùng để nói rằng bạn đang cảm thấy không khỏe hoặc hơi ốm, nhưng không nghiêm trọng. Thường dùng trong ngữ cảnh không trang trọng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_get_the_ball_rolling',
      term: 'get the ball rolling',
      language: 'en',
      meaning_vi: 'bắt đầu công việc, khởi động một hoạt động',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "Let's get the ball rolling on the new project.",
      example_vi: 'Hãy bắt đầu triển khai dự án mới thôi.',
      difficulty: 'B2',
      topics: ['work', 'action'],
      entry_type: 'phrase',
      explanation:
        'Dùng để khuyến khích bắt đầu một công việc hoặc dự án. Thường dùng trong môi trường công sở hoặc cuộc họp.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_on_the_same_page',
      term: 'on the same page',
      language: 'en',
      meaning_vi: 'đồng thuận, hiểu nhau, có cùng quan điểm',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'Before we start, I want to make sure we are all on the same page.',
      example_vi: 'Trước khi bắt đầu, tôi muốn đảm bảo rằng chúng ta đều hiểu nhau.',
      difficulty: 'B1',
      topics: ['work', 'communication'],
      entry_type: 'phrase',
      explanation:
        'Dùng để kiểm tra xem mọi người có cùng hiểu biết hoặc đồng ý với nhau không. Rất phổ biến trong môi trường công sở.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_take_it_with_a_grain_of_salt',
      term: 'take it with a grain of salt',
      language: 'en',
      meaning_vi: 'không nên tin hoàn toàn, cần hoài nghi',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'He tends to exaggerate, so take his stories with a grain of salt.',
      example_vi: 'Anh ấy hay nói quá, vì vậy hãy nghe câu chuyện của anh ấy với một chút hoài nghi.',
      difficulty: 'C1',
      topics: ['communication', 'critical_thinking'],
      entry_type: 'phrase',
      explanation: 'Dùng khi bạn nghi ngờ độ chính xác của thông tin và không nên tin hoàn toàn vào đó.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_bite_the_bullet',
      term: 'bite the bullet',
      language: 'en',
      meaning_vi: 'chịu đựng tình huống khó khăn, dũng cảm đối mặt',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'The surgery was scary, but I had to bite the bullet and go through with it.',
      example_vi: 'Ca phẫu thuật thật đáng sợ, nhưng tôi phải dũng cảm và thực hiện nó.',
      difficulty: 'B2',
      topics: ['courage', 'decision'],
      entry_type: 'phrase',
      explanation:
        'Dùng khi phải đối mặt với tình huống khó chịu hoặc đau đớn một cách dũng cảm, dù không muốn. Xuất phát từ thời chiến tranh.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_hit_the_nail_on_the_head',
      term: 'hit the nail on the head',
      language: 'en',
      meaning_vi: 'nói/làm đúng vào trọng tâm, nhận xét chính xác',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'You hit the nail on the head with that analysis.',
      example_vi: 'Bạn đã phân tích rất đúng trọng tâm.',
      difficulty: 'B2',
      topics: ['communication', 'accuracy'],
      entry_type: 'phrase',
      explanation: 'Dùng để khen ngợi ai đó vì họ đã nhận xét, phân tích hoặc giải thích một điều gì đó rất chính xác.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_pull_someones_leg',
      term: "pull someone's leg",
      language: 'en',
      meaning_vi: 'trêu đùa ai, nói đùa để khiến họ tin',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "Don't worry, I was just pulling your leg!",
      example_vi: 'Đừng lo, tôi chỉ đang trêu bạn thôi!',
      difficulty: 'B1',
      topics: ['humor', 'social'],
      entry_type: 'phrase',
      explanation:
        'Dùng khi bạn đang đùa với ai đó hoặc nói điều gì đó không thật để xem phản ứng của họ. Thường dùng trong ngữ cảnh thân mật, vui vẻ.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_burn_the_midnight_oil',
      term: 'burn the midnight oil',
      language: 'en',
      meaning_vi: 'làm việc/học tập đến tận khuya',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'She burned the midnight oil to finish the report.',
      example_vi: 'Cô ấy thức khuya để hoàn thành báo cáo.',
      difficulty: 'B2',
      topics: ['work', 'study'],
      entry_type: 'phrase',
      explanation: 'Dùng để mô tả việc làm việc hoặc học tập đến rất muộn vào ban đêm. Xuất phát từ thời dùng đèn dầu.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'phrase_speak_of_the_devil',
      term: 'speak of the devil',
      language: 'en',
      meaning_vi: 'vừa nhắc đến ai là họ xuất hiện',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'Speak of the devil — we were just talking about you!',
      example_vi: 'Vừa nhắc đến là thấy — chúng tôi vừa nói chuyện về bạn đấy!',
      difficulty: 'B1',
      topics: ['social', 'humor'],
      entry_type: 'phrase',
      explanation:
        'Dùng khi người đang được nhắc đến bỗng nhiên xuất hiện. Thường nói trong tình huống ngạc nhiên và vui vẻ.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    // ── English idioms (en-idioms track) ─────────────────────────────────────
    {
      id: 'idiom_en_kick_the_bucket',
      term: 'kick the bucket',
      language: 'en-idioms',
      meaning_vi: 'chết (thông tục, hài hước)',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'The old cat finally kicked the bucket last night.',
      example_vi: 'Con mèo già cuối cùng đã ra đi tối qua.',
      difficulty: 'B2',
      topics: ['informal', 'death'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ thông tục, hài hước dùng để nói về cái chết. KHÔNG dùng trong ngữ cảnh trang trọng hoặc chia buồn. Chỉ dùng với người quen hoặc trong văn viết hài hước.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_barking_up_the_wrong_tree',
      term: 'bark up the wrong tree',
      language: 'en-idioms',
      meaning_vi: 'đi sai hướng, nghi oan cho nhầm người',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "If you think I took your pen, you're barking up the wrong tree.",
      example_vi: 'Nếu bạn nghĩ tôi lấy bút của bạn, bạn đang nghi oan người rồi.',
      difficulty: 'B2',
      topics: ['accusation', 'mistake'],
      entry_type: 'idiom',
      explanation: 'Dùng khi ai đó đang theo đuổi sai hướng hoặc đổ lỗi cho nhầm người/nguyên nhân.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_spill_the_beans',
      term: 'spill the beans',
      language: 'en-idioms',
      meaning_vi: 'tiết lộ bí mật, lỡ miệng nói ra điều bí mật',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "Don't spill the beans — it's a surprise party!",
      example_vi: 'Đừng tiết lộ nhé — đây là bữa tiệc bí mật!',
      difficulty: 'B1',
      topics: ['secret', 'social'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi ai đó vô tình hoặc cố ý tiết lộ một bí mật. Thường dùng trong ngữ cảnh nhẹ nhàng, không trang trọng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_the_ball_is_in_your_court',
      term: 'the ball is in your court',
      language: 'en-idioms',
      meaning_vi: 'đến lượt bạn quyết định, bạn có quyền chọn',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "I've made my offer — the ball is in your court now.",
      example_vi: 'Tôi đã đưa ra đề nghị — giờ đến lượt bạn quyết định.',
      difficulty: 'B2',
      topics: ['decision', 'negotiation'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi bạn đã làm hết phần của mình và bây giờ người kia phải đưa ra quyết định hoặc hành động. Xuất phát từ tennis.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_cost_an_arm_and_a_leg',
      term: 'cost an arm and a leg',
      language: 'en-idioms',
      meaning_vi: 'rất đắt tiền, tốn kém vô cùng',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'That car costs an arm and a leg.',
      example_vi: 'Chiếc xe đó đắt kinh khủng.',
      difficulty: 'B1',
      topics: ['money', 'shopping'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi nói về giá cả rất cao, đắt đến mức "phải trả cả tay chân". Dùng phổ biến trong hội thoại hàng ngày.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_let_the_cat_out_of_the_bag',
      term: 'let the cat out of the bag',
      language: 'en-idioms',
      meaning_vi: 'vô tình tiết lộ bí mật',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'She let the cat out of the bag about the surprise wedding.',
      example_vi: 'Cô ấy vô tình tiết lộ về đám cưới bất ngờ.',
      difficulty: 'B1',
      topics: ['secret', 'mistake'],
      entry_type: 'idiom',
      explanation:
        'Giống "spill the beans" nhưng thường nhấn mạnh vào sự vô tình hơn. Dùng khi ai đó lỡ tiết lộ điều được giữ bí mật.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_hit_the_sack',
      term: 'hit the sack',
      language: 'en-idioms',
      meaning_vi: 'đi ngủ',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "I'm exhausted — I'm going to hit the sack.",
      example_vi: 'Tôi mệt quá rồi — tôi đi ngủ đây.',
      difficulty: 'A2',
      topics: ['sleep', 'daily'],
      entry_type: 'idiom',
      explanation:
        'Cách nói thông tục, thân mật về việc đi ngủ. Dùng phổ biến trong giao tiếp hàng ngày với người quen.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_once_in_a_blue_moon',
      term: 'once in a blue moon',
      language: 'en-idioms',
      meaning_vi: 'rất hiếm khi, lâu lâu mới có một lần',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'He visits his family once in a blue moon.',
      example_vi: 'Anh ấy rất hiếm khi về thăm gia đình.',
      difficulty: 'B1',
      topics: ['frequency', 'time'],
      entry_type: 'idiom',
      explanation:
        'Dùng để chỉ điều gì đó xảy ra rất ít, rất hiếm khi. "Blue moon" trong tiếng Anh chỉ trăng tròn lần hai trong một tháng — rất hiếm.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_bite_off_more_than_you_can_chew',
      term: 'bite off more than you can chew',
      language: 'en-idioms',
      meaning_vi: 'nhận quá nhiều việc hơn khả năng xử lý',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'She bit off more than she could chew by taking on five projects at once.',
      example_vi: 'Cô ấy đã nhận quá nhiều khi cùng lúc ôm năm dự án.',
      difficulty: 'B2',
      topics: ['work', 'overload'],
      entry_type: 'idiom',
      explanation: 'Dùng khi ai đó cam kết hoặc nhận lãnh quá nhiều trách nhiệm hơn mức họ có thể hoàn thành tốt.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_a_penny_for_your_thoughts',
      term: 'a penny for your thoughts',
      language: 'en-idioms',
      meaning_vi: 'bạn đang nghĩ gì vậy? (hỏi khi thấy ai đó trầm ngâm)',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "You've been quiet all evening — a penny for your thoughts.",
      example_vi: 'Bạn im lặng cả tối — bạn đang nghĩ gì vậy?',
      difficulty: 'B2',
      topics: ['emotion', 'social'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi hỏi thăm người đang trầm ngâm hoặc im lặng một cách thân thiện. Mang tính quan tâm, không trang trọng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_add_fuel_to_the_fire',
      term: 'add fuel to the fire',
      language: 'en-idioms',
      meaning_vi: 'đổ thêm dầu vào lửa, làm tình hình tệ hơn',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'His comment only added fuel to the fire during the argument.',
      example_vi: 'Bình luận của anh ấy chỉ càng làm cho cuộc tranh cãi thêm căng thẳng.',
      difficulty: 'B2',
      topics: ['conflict', 'emotion'],
      entry_type: 'idiom',
      explanation: 'Dùng khi ai đó làm cho một tình huống vốn đã xấu trở nên tệ hơn, thường là vô ý.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_beat_around_the_bush',
      term: 'beat around the bush',
      language: 'en-idioms',
      meaning_vi: 'vòng vo tam quốc, không nói thẳng vào vấn đề',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "Stop beating around the bush and tell me what's wrong.",
      example_vi: 'Đừng vòng vo nữa, nói thẳng cho tôi biết chuyện gì đang xảy ra đi.',
      difficulty: 'B1',
      topics: ['communication', 'honesty'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi ai đó cứ nói quanh co mà không đi thẳng vào điểm chính. Thường dùng để yêu cầu người khác nói thẳng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_no_pain_no_gain',
      term: 'no pain, no gain',
      language: 'en-idioms',
      meaning_vi: 'không có nỗ lực thì không có thành quả, có công mài sắt có ngày nên kim',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'Keep training — no pain, no gain!',
      example_vi: 'Tiếp tục luyện tập đi — có công mài sắt có ngày nên kim!',
      difficulty: 'A2',
      topics: ['motivation', 'effort'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ động viên: muốn đạt kết quả thì phải chịu khó, chịu cực. Thường dùng trong ngữ cảnh thể thao, học tập hoặc công việc.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_the_last_straw',
      term: 'the last straw',
      language: 'en-idioms',
      meaning_vi: 'giọt nước tràn ly, điều cuối cùng làm bùng phát sự chịu đựng',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'When he was late for the third time, it was the last straw for the manager.',
      example_vi: 'Khi anh ấy đến trễ lần thứ ba, đó là giọt nước tràn ly đối với người quản lý.',
      difficulty: 'B2',
      topics: ['frustration', 'limit'],
      entry_type: 'idiom',
      explanation:
        'Dùng để chỉ hành động cuối cùng trong một chuỗi sự cố khiến ai đó mất kiên nhẫn hoàn toàn. Từ hình ảnh con lạc đà bị gãy lưng vì thêm một cọng rơm.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_see_eye_to_eye',
      term: 'see eye to eye',
      language: 'en-idioms',
      meaning_vi: 'đồng ý với nhau, có cùng quan điểm',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "My sister and I don't always see eye to eye on politics.",
      example_vi: 'Chị gái tôi và tôi không phải lúc nào cũng đồng quan điểm về chính trị.',
      difficulty: 'B1',
      topics: ['agreement', 'opinion'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi hai người có cùng ý kiến hoặc quan điểm. Thường dùng trong câu phủ định để nói về sự bất đồng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_sit_on_the_fence',
      term: 'sit on the fence',
      language: 'en-idioms',
      meaning_vi: 'trung lập, không chọn bên nào, không dám quyết định',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'Stop sitting on the fence and give us your opinion.',
      example_vi: 'Đừng trung lập mãi nữa, hãy cho chúng tôi biết ý kiến của bạn.',
      difficulty: 'B2',
      topics: ['decision', 'opinion'],
      entry_type: 'idiom',
      explanation: 'Dùng khi ai đó cố tình không chọn một bên trong tranh luận hoặc từ chối đưa ra quan điểm rõ ràng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_in_the_same_boat',
      term: 'in the same boat',
      language: 'en-idioms',
      meaning_vi: 'cùng hoàn cảnh, cùng chịu vấn đề như nhau',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "We're all in the same boat when it comes to the budget cuts.",
      example_vi: 'Tất cả chúng ta đều đang ở cùng hoàn cảnh khi đối mặt với việc cắt giảm ngân sách.',
      difficulty: 'B1',
      topics: ['solidarity', 'situation'],
      entry_type: 'idiom',
      explanation:
        'Dùng để thể hiện sự đoàn kết: mọi người cùng ở trong hoàn cảnh giống nhau, thường là hoàn cảnh khó khăn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_actions_speak_louder_than_words',
      term: 'actions speak louder than words',
      language: 'en-idioms',
      meaning_vi: 'hành động quan trọng hơn lời nói',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: "Don't just promise to help — actions speak louder than words.",
      example_vi: 'Đừng chỉ hứa hẹn — hành động quan trọng hơn lời nói.',
      difficulty: 'A2',
      topics: ['character', 'behavior'],
      entry_type: 'idiom',
      explanation:
        'Ngạn ngữ quen thuộc nhấn mạnh rằng điều bạn làm có ý nghĩa hơn điều bạn nói. Dùng được trong mọi ngữ cảnh.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_a_blessing_in_disguise',
      term: 'a blessing in disguise',
      language: 'en-idioms',
      meaning_vi: 'điều tưởng là xấu nhưng lại mang lại kết quả tốt',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'Losing that job was a blessing in disguise — I found a much better one.',
      example_vi: 'Mất việc đó hóa ra lại là điều may — tôi tìm được công việc tốt hơn nhiều.',
      difficulty: 'B2',
      topics: ['optimism', 'life'],
      entry_type: 'idiom',
      explanation: 'Dùng khi điều ban đầu tưởng là bất hạnh hoặc tệ lại dẫn đến kết quả tốt đẹp.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_hit_the_nail_on_head',
      term: 'hit the nail on the head',
      language: 'en-idioms',
      meaning_vi: 'nhận xét đúng trọng tâm, đánh giá chính xác',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'You hit the nail on the head with that diagnosis.',
      example_vi: 'Chẩn đoán của bạn hoàn toàn chính xác.',
      difficulty: 'B2',
      topics: ['accuracy', 'praise'],
      entry_type: 'idiom',
      explanation: 'Dùng để khen ngợi ai đó vì họ xác định đúng vấn đề hoặc đưa ra nhận xét chính xác.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_en_throw_in_the_towel',
      term: 'throw in the towel',
      language: 'en-idioms',
      meaning_vi: 'bỏ cuộc, chấp nhận thất bại',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: '',
      example: 'After months of trying, he finally threw in the towel.',
      example_vi: 'Sau nhiều tháng cố gắng, cuối cùng anh ấy đã bỏ cuộc.',
      difficulty: 'B2',
      topics: ['defeat', 'persistence'],
      entry_type: 'idiom',
      explanation:
        'Dùng khi ai đó quyết định ngừng cố gắng và chấp nhận thất bại. Xuất phát từ quyền anh: góc ném khăn vào sàn đấu là dấu hiệu đầu hàng.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    // ── Chinese idioms (zh-idioms track) ─────────────────────────────────────
    {
      id: 'idiom_zh_yi_shi_er_niao',
      term: '一石二鸟',
      language: 'zh-idioms',
      meaning_vi: 'một mũi tên trúng hai đích',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'yī shí èr niǎo',
      example: '这个方案一石二鸟，既省钱又省时间。',
      example_vi: 'Kế hoạch này một mũi tên trúng hai đích — vừa tiết kiệm tiền vừa tiết kiệm thời gian.',
      difficulty: 'HSK4',
      topics: ['strategy', 'efficiency'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ (成语). Nghĩa đen: "một viên đá, hai con chim". Dùng khi một hành động đạt được hai mục tiêu cùng lúc. Tương đương "kill two birds with one stone" trong tiếng Anh.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_ma_dao_cheng_gong',
      term: '马到成功',
      language: 'zh-idioms',
      meaning_vi: 'thành công ngay từ đầu, mọi việc đều suôn sẻ',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'mǎ dào chéng gōng',
      example: '祝你考试马到成功！',
      example_vi: 'Chúc bạn thi cử thành công thuận lợi!',
      difficulty: 'HSK4',
      topics: ['blessing', 'success'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "ngựa đến là thành công". Dùng như lời chúc tốt đẹp trước khi ai đó bắt đầu một việc quan trọng. Rất phổ biến trong văn hóa Trung Hoa.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_han_jia_hu_wei',
      term: '狐假虎威',
      language: 'zh-idioms',
      meaning_vi: 'dựa hơi kẻ mạnh để ra oai, hù dọa người khác',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'hú jiǎ hǔ wēi',
      example: '他靠着老板的关系狐假虎威，欺负同事。',
      example_vi: 'Anh ta dựa vào mối quan hệ với sếp để ra oai, bắt nạt đồng nghiệp.',
      difficulty: 'HSK5',
      topics: ['power', 'bullying'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "cáo mượn oai hùm". Xuất phát từ câu chuyện con cáo dắt hổ đi để các thú vật khác sợ hùm mà tránh né cáo. Dùng khi ai đó lợi dụng uy thế của người khác.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_ban_men_nong_fu',
      term: '班门弄斧',
      language: 'zh-idioms',
      meaning_vi: 'múa rìu qua mắt thợ, khoe tài trước mặt người giỏi hơn',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'bān mén nòng fǔ',
      example: '在这位大师面前谈绘画，真是班门弄斧。',
      example_vi: 'Bàn về hội họa trước mặt vị đại sư này thật là múa rìu qua mắt thợ.',
      difficulty: 'HSK5',
      topics: ['humility', 'skill'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "múa búa trước cửa nhà ông Ban (Lu Ban — thợ mộc tài ba nhất)". Dùng khi ai đó cố khoe tài năng trước người giỏi hơn nhiều, thường mang tính tự trào.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_tuo_bu_rao_ren',
      term: '得寸进尺',
      language: 'zh-idioms',
      meaning_vi: 'được đằng chân lân đằng đầu, tham lam không biết dừng',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'dé cùn jìn chǐ',
      example: '你已经帮了他很多了，别让他得寸进尺。',
      example_vi: 'Bạn đã giúp anh ta rất nhiều rồi, đừng để anh ta được đằng chân lân đằng đầu.',
      difficulty: 'HSK5',
      topics: ['greed', 'behavior'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "được tấc lại đòi thước". Dùng để chỉ người tham lam, được một thì muốn hai, không biết đủ.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_ji_bu_ze_shi',
      term: '饥不择食',
      language: 'zh-idioms',
      meaning_vi: 'đói thì ăn bất cứ thứ gì, hoàn cảnh ép buộc không được chọn lựa',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'jī bù zé shí',
      example: '现在工作难找，饥不择食，先做这份工作吧。',
      example_vi: 'Hiện tại việc làm khó tìm, không được chọn lựa, cứ làm công việc này đã.',
      difficulty: 'HSK5',
      topics: ['necessity', 'desperation'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "đói không chọn thức ăn". Dùng khi hoàn cảnh bắt buộc phải chấp nhận những gì có, không thể đòi hỏi.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_hua_she_tian_zu',
      term: '画蛇添足',
      language: 'zh-idioms',
      meaning_vi: 'vẽ rắn thêm chân, làm thêm điều không cần thiết gây hỏng việc',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'huà shé tiān zú',
      example: '报告已经很完整了，别再修改了，画蛇添足反而不好。',
      example_vi: 'Báo cáo đã hoàn chỉnh rồi, đừng sửa thêm nữa, vẽ rắn thêm chân lại hỏng.',
      difficulty: 'HSK4',
      topics: ['mistake', 'overdo'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ xuất phát từ câu chuyện người vẽ rắn nhanh nhất nhưng lại thêm chân vào nên thua. Dùng khi ai đó làm thêm điều không cần thiết khiến việc trở nên tệ hơn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_ye_gong_hao_long',
      term: '叶公好龙',
      language: 'zh-idioms',
      meaning_vi: 'giả vờ yêu thích điều gì nhưng thực ra sợ hãi khi đối mặt thật',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'yè gōng hào lóng',
      example: '他说自己喜欢挑战，其实叶公好龙，遇到真正的困难就退缩了。',
      example_vi: 'Anh ta nói thích thử thách, thực ra chỉ là thích nói, khi gặp khó khăn thật sự là lui ngay.',
      difficulty: 'HSK6',
      topics: ['hypocrisy', 'character'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Xuất phát từ câu chuyện ông Diệp Công thích rồng trong tranh nhưng khi rồng thật xuất hiện thì sợ hãi. Dùng khi ai đó nói thích điều gì nhưng thực ra không thật sự muốn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_mao_dun',
      term: '自相矛盾',
      language: 'zh-idioms',
      meaning_vi: 'tự mâu thuẫn với chính mình',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'zì xiāng máo dùn',
      example: '他的解释自相矛盾，让人无法相信。',
      example_vi: 'Giải thích của anh ấy tự mâu thuẫn, khiến người ta không thể tin.',
      difficulty: 'HSK4',
      topics: ['logic', 'contradiction'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Xuất phát từ câu chuyện người bán giáo và khiên: nói giáo của mình đâm thủng mọi thứ, lại nói khiên của mình không gì đâm thủng được. Dùng khi ai đó nói điều mâu thuẫn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_lang_bei_wei_jian',
      term: '狼狈为奸',
      language: 'zh-idioms',
      meaning_vi: 'câu kết với nhau để làm điều xấu',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'láng bèi wéi jiān',
      example: '他们两个人狼狈为奸，一起欺骗顾客。',
      example_vi: 'Hai người đó câu kết với nhau để lừa khách hàng.',
      difficulty: 'HSK6',
      topics: ['collusion', 'evil'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "sói và gấu trúc cùng nhau làm ác". Dùng khi hai hay nhiều người bất lương hợp tác để làm điều xấu.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_gua_mu_xiang_kan',
      term: '刮目相看',
      language: 'zh-idioms',
      meaning_vi: 'nhìn nhận lại ai với con mắt khác, thay đổi cái nhìn về ai đó',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'guā mù xiāng kàn',
      example: '他的进步让所有人刮目相看。',
      example_vi: 'Sự tiến bộ của anh ấy khiến mọi người phải nhìn nhận lại.',
      difficulty: 'HSK5',
      topics: ['impression', 'change'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "lau mắt mà nhìn". Dùng khi ai đó đã thay đổi đến mức người khác phải thay đổi quan điểm về họ, thường theo hướng tích cực.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_jie_cao_xian_sheng',
      term: '借刀杀人',
      language: 'zh-idioms',
      meaning_vi: 'mượn tay người khác để hại kẻ thù, dùng người khác làm công cụ',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'jiè dāo shā rén',
      example: '他借刀杀人，让同事去得罪了领导。',
      example_vi: 'Anh ta mượn tay người khác, khiến đồng nghiệp đắc tội với lãnh đạo.',
      difficulty: 'HSK6',
      topics: ['manipulation', 'strategy'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "mượn dao giết người". Một trong 36 kế. Dùng khi ai đó không trực tiếp ra tay mà dùng người thứ ba để đối phó với kẻ thù.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_qian_lu_yi_de',
      term: '千虑一得',
      language: 'zh-idioms',
      meaning_vi: 'trong ngàn lần suy nghĩ ắt có lần đúng, kẻ ngu cũng có lúc có ý hay',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'qiān lǜ yī dé',
      example: '我虽然不聪明，但千虑一得，也许这个想法值得考虑。',
      example_vi: 'Tôi tuy không thông minh, nhưng đôi khi cũng có ý hay, có lẽ ý tưởng này đáng xem xét.',
      difficulty: 'HSK6',
      topics: ['humility', 'wisdom'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Dùng để khiêm tốn khi đề xuất ý kiến, ngụ ý "tôi biết mình không giỏi nhưng biết đâu lại có điều đúng". Là cách nói khiêm tốn lịch sự trong văn hóa Trung Hoa.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_shou_zhu_dai_tu',
      term: '守株待兔',
      language: 'zh-idioms',
      meaning_vi: 'thụ động chờ may mắn, không chịu cố gắng mà chờ vận may',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'shǒu zhū dài tù',
      example: '不能守株待兔，要主动去寻找机会。',
      example_vi: 'Không thể thụ động chờ đợi, phải chủ động tìm kiếm cơ hội.',
      difficulty: 'HSK4',
      topics: ['effort', 'passivity'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Xuất phát từ câu chuyện người nông dân thấy thỏ chạy vào gốc cây chết, rồi bỏ ruộng ngồi chờ có thỏ nữa. Dùng để phê bình sự thụ động, ỷ lại vào may mắn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_za_jing_guan_tian',
      term: '坐井观天',
      language: 'zh-idioms',
      meaning_vi: 'ếch ngồi đáy giếng nhìn trời, tầm nhìn hạn hẹp',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'zuò jǐng guān tiān',
      example: '他从没出过国，眼界太窄，真是坐井观天。',
      example_vi: 'Anh ta chưa từng ra nước ngoài, tầm nhìn quá hẹp, đúng là ếch ngồi đáy giếng.',
      difficulty: 'HSK4',
      topics: ['perspective', 'ignorance'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "ngồi trong giếng nhìn bầu trời". Dùng để phê bình người có tầm nhìn hạn hẹp, thiếu hiểu biết về thế giới rộng lớn hơn.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_zhi_zu_chang_le',
      term: '知足常乐',
      language: 'zh-idioms',
      meaning_vi: 'biết đủ thì luôn vui, không tham lam thì hạnh phúc',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'zhī zú cháng lè',
      example: '生活不必太奢华，知足常乐才是真正的幸福。',
      example_vi: 'Cuộc sống không cần quá xa hoa, biết đủ thì luôn vui mới là hạnh phúc thật sự.',
      difficulty: 'HSK4',
      topics: ['happiness', 'contentment'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ/ngạn ngữ 4 chữ. Triết lý Lão Tử: người biết bằng lòng với những gì mình có sẽ luôn tìm thấy hạnh phúc. Dùng như lời khuyên hoặc triết lý sống.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_lao_ma_shi_tu',
      term: '老马识途',
      language: 'zh-idioms',
      meaning_vi: 'ngựa già biết đường, người có kinh nghiệm biết cách xử lý',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'lǎo mǎ shí tú',
      example: '他在这行业做了三十年，老马识途，交给他就放心了。',
      example_vi: 'Ông ấy làm trong ngành này ba mươi năm, kinh nghiệm dày dặn, giao cho ông ấy là yên tâm.',
      difficulty: 'HSK5',
      topics: ['experience', 'wisdom'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Xuất phát từ câu chuyện Quản Trọng thả ngựa già dẫn đường khi bị lạc. Dùng để ca ngợi kinh nghiệm và trí tuệ thực tế của người lớn tuổi.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_yi_jian_zhong_di',
      term: '一针见血',
      language: 'zh-idioms',
      meaning_vi: 'nói thẳng vào trọng tâm, phân tích sắc bén',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'yī zhēn jiàn xiě',
      example: '他的分析一针见血，大家都点头称是。',
      example_vi: 'Phân tích của anh ấy đi thẳng vào vấn đề, mọi người đều gật đầu đồng ý.',
      difficulty: 'HSK5',
      topics: ['analysis', 'directness'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Nghĩa đen: "một mũi kim thấy máu ngay". Dùng để khen ngợi người có khả năng phân tích, nhận xét sắc bén và đi thẳng vào vấn đề.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_shui_dao_qu_cheng',
      term: '水到渠成',
      language: 'zh-idioms',
      meaning_vi: 'nước đến thì mương thành, điều kiện đủ thì việc tự nhiên thành công',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'shuǐ dào qú chéng',
      example: '只要坚持努力，水到渠成，成功是迟早的事。',
      example_vi: 'Chỉ cần kiên trì nỗ lực, điều kiện đủ thì việc sẽ tự thành, thành công chỉ là vấn đề thời gian.',
      difficulty: 'HSK5',
      topics: ['patience', 'success'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Triết lý: khi điều kiện chín muồi, kết quả sẽ tự nhiên đến. Dùng để khuyến khích kiên nhẫn chờ đợi đúng thời điểm.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    },
    {
      id: 'idiom_zh_ban_tu_er_fei',
      term: '半途而废',
      language: 'zh-idioms',
      meaning_vi: 'bỏ giữa chừng, không kiên trì đến cùng',
      part_of_speech: '',
      ipa: '',
      vietnamese_pronunciation: 'bàn tú ér fèi',
      example: '学习语言不能半途而废，要坚持下去。',
      example_vi: 'Học ngôn ngữ không thể bỏ giữa chừng, phải kiên trì đến cùng.',
      difficulty: 'HSK4',
      topics: ['persistence', 'failure'],
      entry_type: 'idiom',
      explanation:
        'Thành ngữ 4 chữ. Dùng để phê bình việc bỏ cuộc giữa chừng trước khi hoàn thành mục tiêu. Thường dùng như lời cảnh báo hoặc phê bình.',
      generation_source: 'seed',
      created_at: now,
      updated_at: now
    }
  ];
}
