-- Add viet_reading_text column to memorization_segments.
-- Stores Vietnamese phonetic approximation of the segment text,
-- generated by the enrichment LLM alongside ipa_text and translation_text.
-- Nullable: existing segments retain NULL until re-enriched.

ALTER TABLE memorization_segments
  ADD COLUMN IF NOT EXISTS viet_reading_text TEXT;
