// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/data/local_database_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3340211202052680839),
    name: 'AppLogEntity',
    lastPropertyId: const obx_int.IdUid(8, 6491801115652478530),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 845055066740814255),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5847377801899736720),
        name: 'timestampMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(1, 6191300927395045658),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7377388880024789569),
        name: 'level',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 7513863851905780472),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 143948075617569385),
        name: 'category',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 4425557790247910166),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4592707537784256094),
        name: 'event',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 97130024336644438),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1126066632101733900),
        name: 'traceId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6491801115652478530),
        name: 'contextJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6168246856299936119),
    name: 'AppSettingEntity',
    lastPropertyId: const obx_int.IdUid(3, 6918187452517430412),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6789012644431816584),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4785677649717544553),
        name: 'key',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(4, 5324061080787563317),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6918187452517430412),
        name: 'value',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8516035737042230106),
    name: 'LocalWordEntity',
    lastPropertyId: const obx_int.IdUid(18, 437125655485656215),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7989027724147477812),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8277228887757568832),
        name: 'localId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(5, 7288440386876964350),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 731815490182437082),
        name: 'serverWordId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 7832971388181166745),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3243454725922913435),
        name: 'term',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8870422477911700984),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8703359030412233347),
        name: 'meaningVi',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4746957429690680180),
        name: 'partOfSpeech',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3173119652878193097),
        name: 'ipa',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6154928956634931446),
        name: 'vietnamesePronunciation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2780256073354670570),
        name: 'example',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 4901705087076275622),
        name: 'exampleVi',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 803599193384346319),
        name: 'difficulty',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8504748601961848488),
        name: 'topicsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8251074300126283887),
        name: 'status',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 8184121286975796185),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 901071489992355650),
        name: 'lastSeenAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(8, 3425236340869465553),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 617905263441262378),
        name: 'nextReviewAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(9, 8841299430443541294),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8474386067916702066),
        name: 'createdAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(10, 2775067309935092816),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 437125655485656215),
        name: 'updatedAtMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5597746502529587288),
    name: 'StudyEventEntity',
    lastPropertyId: const obx_int.IdUid(7, 3549979123076235846),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8443910705140584466),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7151618397635527488),
        name: 'clientEventId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(11, 3826929843723604731),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6106597315587673488),
        name: 'localWordId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7120067178825931438),
        name: 'serverWordId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2326854486458290231),
        name: 'rating',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7301545010915554520),
        name: 'occurredAtMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3549979123076235846),
        name: 'syncStatus',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 5120231743551883184),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 1182565041746058355),
    name: 'SyncQueueEntity',
    lastPropertyId: const obx_int.IdUid(6, 4601925741032122636),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8430649181488831598),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9000703130567815539),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7821784636335834819),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7145660166919742887),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6012074988658042269),
        name: 'nextRetryAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 1917521521677049276),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4601925741032122636),
        name: 'createdAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(14, 1997602164196919271),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 184519167541283189),
    name: 'SpeakingAttemptEntity',
    lastPropertyId: const obx_int.IdUid(10, 4571414392161499582),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4860408431035195995),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7751347899719781995),
        name: 'attemptId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(15, 136311804813454643),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1345673362050694855),
        name: 'promptId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(16, 6217275210855706911),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7887357254154021418),
        name: 'serverWordId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(17, 5254615947711722057),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2774356376887323931),
        name: 'occurredAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(18, 775476222157682369),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7850533391135794604),
        name: 'durationMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2976845626310034898),
        name: 'retryCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3897988403733548072),
        name: 'selfRating',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 2978807451352632217),
        name: 'syncStatus',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(19, 6835893711145020477),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4571414392161499582),
        name: 'localAudioPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5907671979540824477),
    name: 'SpeakingPromptEntity',
    lastPropertyId: const obx_int.IdUid(12, 5819468243168209987),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 718334415471620391),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1300126683820559034),
        name: 'promptId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(20, 4210664322592183295),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3997792870214344037),
        name: 'wordSenseId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(21, 8218318912247925168),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8975047045818945915),
        name: 'serverWordId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(22, 6566907388555771660),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3212794834144958348),
        name: 'targetText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3155788786499248033),
        name: 'viHint',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3692318380675609575),
        name: 'targetPhrase',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2489710014958849740),
        name: 'pronunciationTip',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5273269794502570518),
        name: 'commonMistake',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5391782460491484301),
        name: 'difficulty',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 331387211832234939),
        name: 'topic',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5819468243168209987),
        name: 'cachedAtMs',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(23, 6588260673035546186),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(7, 5907671979540824477),
    lastIndexId: const obx_int.IdUid(23, 6588260673035546186),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AppLogEntity: obx_int.EntityDefinition<AppLogEntity>(
      model: _entities[0],
      toOneRelations: (AppLogEntity object) => [],
      toManyRelations: (AppLogEntity object) => {},
      getId: (AppLogEntity object) => object.id,
      setId: (AppLogEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppLogEntity object, fb.Builder fbb) {
        final levelOffset = fbb.writeString(object.level);
        final categoryOffset = fbb.writeString(object.category);
        final eventOffset = fbb.writeString(object.event);
        final messageOffset = fbb.writeString(object.message);
        final traceIdOffset = object.traceId == null
            ? null
            : fbb.writeString(object.traceId!);
        final contextJsonOffset = fbb.writeString(object.contextJson);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.timestampMs);
        fbb.addOffset(2, levelOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addOffset(4, eventOffset);
        fbb.addOffset(5, messageOffset);
        fbb.addOffset(6, traceIdOffset);
        fbb.addOffset(7, contextJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final timestampMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final levelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final eventParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final traceIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final contextJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = AppLogEntity(
          id: idParam,
          timestampMs: timestampMsParam,
          level: levelParam,
          category: categoryParam,
          event: eventParam,
          message: messageParam,
          traceId: traceIdParam,
          contextJson: contextJsonParam,
        );

        return object;
      },
    ),
    AppSettingEntity: obx_int.EntityDefinition<AppSettingEntity>(
      model: _entities[1],
      toOneRelations: (AppSettingEntity object) => [],
      toManyRelations: (AppSettingEntity object) => {},
      getId: (AppSettingEntity object) => object.id,
      setId: (AppSettingEntity object, int id) {
        object.id = id;
      },
      objectToFB: (AppSettingEntity object, fb.Builder fbb) {
        final keyOffset = fbb.writeString(object.key);
        final valueOffset = fbb.writeString(object.value);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, keyOffset);
        fbb.addOffset(2, valueOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final keyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final valueParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = AppSettingEntity(
          id: idParam,
          key: keyParam,
          value: valueParam,
        );

        return object;
      },
    ),
    LocalWordEntity: obx_int.EntityDefinition<LocalWordEntity>(
      model: _entities[2],
      toOneRelations: (LocalWordEntity object) => [],
      toManyRelations: (LocalWordEntity object) => {},
      getId: (LocalWordEntity object) => object.id,
      setId: (LocalWordEntity object, int id) {
        object.id = id;
      },
      objectToFB: (LocalWordEntity object, fb.Builder fbb) {
        final localIdOffset = fbb.writeString(object.localId);
        final serverWordIdOffset = object.serverWordId == null
            ? null
            : fbb.writeString(object.serverWordId!);
        final termOffset = fbb.writeString(object.term);
        final languageOffset = fbb.writeString(object.language);
        final meaningViOffset = fbb.writeString(object.meaningVi);
        final partOfSpeechOffset = object.partOfSpeech == null
            ? null
            : fbb.writeString(object.partOfSpeech!);
        final ipaOffset = fbb.writeString(object.ipa);
        final vietnamesePronunciationOffset = fbb.writeString(
          object.vietnamesePronunciation,
        );
        final exampleOffset = fbb.writeString(object.example);
        final exampleViOffset = fbb.writeString(object.exampleVi);
        final difficultyOffset = fbb.writeString(object.difficulty);
        final topicsJsonOffset = fbb.writeString(object.topicsJson);
        final statusOffset = fbb.writeString(object.status);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, localIdOffset);
        fbb.addOffset(2, serverWordIdOffset);
        fbb.addOffset(3, termOffset);
        fbb.addOffset(4, languageOffset);
        fbb.addOffset(5, meaningViOffset);
        fbb.addOffset(6, partOfSpeechOffset);
        fbb.addOffset(7, ipaOffset);
        fbb.addOffset(8, vietnamesePronunciationOffset);
        fbb.addOffset(9, exampleOffset);
        fbb.addOffset(10, exampleViOffset);
        fbb.addOffset(11, difficultyOffset);
        fbb.addOffset(12, topicsJsonOffset);
        fbb.addOffset(13, statusOffset);
        fbb.addInt64(14, object.lastSeenAtMs);
        fbb.addInt64(15, object.nextReviewAtMs);
        fbb.addInt64(16, object.createdAtMs);
        fbb.addInt64(17, object.updatedAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final localIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final serverWordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final termParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final languageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final meaningViParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final partOfSpeechParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final ipaParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final vietnamesePronunciationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final exampleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final exampleViParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final difficultyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final topicsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final lastSeenAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final nextReviewAtMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final updatedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          38,
          0,
        );
        final object = LocalWordEntity(
          id: idParam,
          localId: localIdParam,
          serverWordId: serverWordIdParam,
          term: termParam,
          language: languageParam,
          meaningVi: meaningViParam,
          partOfSpeech: partOfSpeechParam,
          ipa: ipaParam,
          vietnamesePronunciation: vietnamesePronunciationParam,
          example: exampleParam,
          exampleVi: exampleViParam,
          difficulty: difficultyParam,
          topicsJson: topicsJsonParam,
          status: statusParam,
          lastSeenAtMs: lastSeenAtMsParam,
          nextReviewAtMs: nextReviewAtMsParam,
          createdAtMs: createdAtMsParam,
          updatedAtMs: updatedAtMsParam,
        );

        return object;
      },
    ),
    StudyEventEntity: obx_int.EntityDefinition<StudyEventEntity>(
      model: _entities[3],
      toOneRelations: (StudyEventEntity object) => [],
      toManyRelations: (StudyEventEntity object) => {},
      getId: (StudyEventEntity object) => object.id,
      setId: (StudyEventEntity object, int id) {
        object.id = id;
      },
      objectToFB: (StudyEventEntity object, fb.Builder fbb) {
        final clientEventIdOffset = fbb.writeString(object.clientEventId);
        final localWordIdOffset = fbb.writeString(object.localWordId);
        final serverWordIdOffset = object.serverWordId == null
            ? null
            : fbb.writeString(object.serverWordId!);
        final ratingOffset = fbb.writeString(object.rating);
        final syncStatusOffset = fbb.writeString(object.syncStatus);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, clientEventIdOffset);
        fbb.addOffset(2, localWordIdOffset);
        fbb.addOffset(3, serverWordIdOffset);
        fbb.addOffset(4, ratingOffset);
        fbb.addInt64(5, object.occurredAtMs);
        fbb.addOffset(6, syncStatusOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final clientEventIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final localWordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final serverWordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final ratingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final occurredAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final syncStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = StudyEventEntity(
          id: idParam,
          clientEventId: clientEventIdParam,
          localWordId: localWordIdParam,
          serverWordId: serverWordIdParam,
          rating: ratingParam,
          occurredAtMs: occurredAtMsParam,
          syncStatus: syncStatusParam,
        );

        return object;
      },
    ),
    SyncQueueEntity: obx_int.EntityDefinition<SyncQueueEntity>(
      model: _entities[4],
      toOneRelations: (SyncQueueEntity object) => [],
      toManyRelations: (SyncQueueEntity object) => {},
      getId: (SyncQueueEntity object) => object.id,
      setId: (SyncQueueEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SyncQueueEntity object, fb.Builder fbb) {
        final typeOffset = fbb.writeString(object.type);
        final payloadOffset = fbb.writeString(object.payload);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, typeOffset);
        fbb.addOffset(2, payloadOffset);
        fbb.addInt64(3, object.retryCount);
        fbb.addInt64(4, object.nextRetryAtMs);
        fbb.addInt64(5, object.createdAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final nextRetryAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final createdAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = SyncQueueEntity(
          id: idParam,
          type: typeParam,
          payload: payloadParam,
          retryCount: retryCountParam,
          nextRetryAtMs: nextRetryAtMsParam,
          createdAtMs: createdAtMsParam,
        );

        return object;
      },
    ),
    SpeakingAttemptEntity: obx_int.EntityDefinition<SpeakingAttemptEntity>(
      model: _entities[5],
      toOneRelations: (SpeakingAttemptEntity object) => [],
      toManyRelations: (SpeakingAttemptEntity object) => {},
      getId: (SpeakingAttemptEntity object) => object.id,
      setId: (SpeakingAttemptEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SpeakingAttemptEntity object, fb.Builder fbb) {
        final attemptIdOffset = fbb.writeString(object.attemptId);
        final promptIdOffset = object.promptId == null
            ? null
            : fbb.writeString(object.promptId!);
        final serverWordIdOffset = object.serverWordId == null
            ? null
            : fbb.writeString(object.serverWordId!);
        final selfRatingOffset = object.selfRating == null
            ? null
            : fbb.writeString(object.selfRating!);
        final syncStatusOffset = fbb.writeString(object.syncStatus);
        final localAudioPathOffset = object.localAudioPath == null
            ? null
            : fbb.writeString(object.localAudioPath!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, attemptIdOffset);
        fbb.addOffset(2, promptIdOffset);
        fbb.addOffset(3, serverWordIdOffset);
        fbb.addInt64(4, object.occurredAtMs);
        fbb.addInt64(5, object.durationMs);
        fbb.addInt64(6, object.retryCount);
        fbb.addOffset(7, selfRatingOffset);
        fbb.addOffset(8, syncStatusOffset);
        fbb.addOffset(9, localAudioPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final attemptIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final promptIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final serverWordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final occurredAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final durationMsParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final retryCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final selfRatingParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final syncStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final localAudioPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final object = SpeakingAttemptEntity(
          id: idParam,
          attemptId: attemptIdParam,
          promptId: promptIdParam,
          serverWordId: serverWordIdParam,
          occurredAtMs: occurredAtMsParam,
          durationMs: durationMsParam,
          retryCount: retryCountParam,
          selfRating: selfRatingParam,
          syncStatus: syncStatusParam,
          localAudioPath: localAudioPathParam,
        );

        return object;
      },
    ),
    SpeakingPromptEntity: obx_int.EntityDefinition<SpeakingPromptEntity>(
      model: _entities[6],
      toOneRelations: (SpeakingPromptEntity object) => [],
      toManyRelations: (SpeakingPromptEntity object) => {},
      getId: (SpeakingPromptEntity object) => object.id,
      setId: (SpeakingPromptEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SpeakingPromptEntity object, fb.Builder fbb) {
        final promptIdOffset = fbb.writeString(object.promptId);
        final wordSenseIdOffset = object.wordSenseId == null
            ? null
            : fbb.writeString(object.wordSenseId!);
        final serverWordIdOffset = object.serverWordId == null
            ? null
            : fbb.writeString(object.serverWordId!);
        final targetTextOffset = object.targetText == null
            ? null
            : fbb.writeString(object.targetText!);
        final viHintOffset = object.viHint == null
            ? null
            : fbb.writeString(object.viHint!);
        final targetPhraseOffset = object.targetPhrase == null
            ? null
            : fbb.writeString(object.targetPhrase!);
        final pronunciationTipOffset = object.pronunciationTip == null
            ? null
            : fbb.writeString(object.pronunciationTip!);
        final commonMistakeOffset = object.commonMistake == null
            ? null
            : fbb.writeString(object.commonMistake!);
        final difficultyOffset = object.difficulty == null
            ? null
            : fbb.writeString(object.difficulty!);
        final topicOffset = object.topic == null
            ? null
            : fbb.writeString(object.topic!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, promptIdOffset);
        fbb.addOffset(2, wordSenseIdOffset);
        fbb.addOffset(3, serverWordIdOffset);
        fbb.addOffset(4, targetTextOffset);
        fbb.addOffset(5, viHintOffset);
        fbb.addOffset(6, targetPhraseOffset);
        fbb.addOffset(7, pronunciationTipOffset);
        fbb.addOffset(8, commonMistakeOffset);
        fbb.addOffset(9, difficultyOffset);
        fbb.addOffset(10, topicOffset);
        fbb.addInt64(11, object.cachedAtMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final promptIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final wordSenseIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final serverWordIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final targetTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final viHintParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final targetPhraseParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final pronunciationTipParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final commonMistakeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final difficultyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final topicParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final cachedAtMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final object = SpeakingPromptEntity(
          id: idParam,
          promptId: promptIdParam,
          wordSenseId: wordSenseIdParam,
          serverWordId: serverWordIdParam,
          targetText: targetTextParam,
          viHint: viHintParam,
          targetPhrase: targetPhraseParam,
          pronunciationTip: pronunciationTipParam,
          commonMistake: commonMistakeParam,
          difficulty: difficultyParam,
          topic: topicParam,
          cachedAtMs: cachedAtMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AppLogEntity] entity fields to define ObjectBox queries.
class AppLogEntity_ {
  /// See [AppLogEntity.id].
  static final id = obx.QueryIntegerProperty<AppLogEntity>(
    _entities[0].properties[0],
  );

  /// See [AppLogEntity.timestampMs].
  static final timestampMs = obx.QueryIntegerProperty<AppLogEntity>(
    _entities[0].properties[1],
  );

  /// See [AppLogEntity.level].
  static final level = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[2],
  );

  /// See [AppLogEntity.category].
  static final category = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[3],
  );

  /// See [AppLogEntity.event].
  static final event = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[4],
  );

  /// See [AppLogEntity.message].
  static final message = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[5],
  );

  /// See [AppLogEntity.traceId].
  static final traceId = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[6],
  );

  /// See [AppLogEntity.contextJson].
  static final contextJson = obx.QueryStringProperty<AppLogEntity>(
    _entities[0].properties[7],
  );
}

/// [AppSettingEntity] entity fields to define ObjectBox queries.
class AppSettingEntity_ {
  /// See [AppSettingEntity.id].
  static final id = obx.QueryIntegerProperty<AppSettingEntity>(
    _entities[1].properties[0],
  );

  /// See [AppSettingEntity.key].
  static final key = obx.QueryStringProperty<AppSettingEntity>(
    _entities[1].properties[1],
  );

  /// See [AppSettingEntity.value].
  static final value = obx.QueryStringProperty<AppSettingEntity>(
    _entities[1].properties[2],
  );
}

/// [LocalWordEntity] entity fields to define ObjectBox queries.
class LocalWordEntity_ {
  /// See [LocalWordEntity.id].
  static final id = obx.QueryIntegerProperty<LocalWordEntity>(
    _entities[2].properties[0],
  );

  /// See [LocalWordEntity.localId].
  static final localId = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[1],
  );

  /// See [LocalWordEntity.serverWordId].
  static final serverWordId = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[2],
  );

  /// See [LocalWordEntity.term].
  static final term = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[3],
  );

  /// See [LocalWordEntity.language].
  static final language = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[4],
  );

  /// See [LocalWordEntity.meaningVi].
  static final meaningVi = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[5],
  );

  /// See [LocalWordEntity.partOfSpeech].
  static final partOfSpeech = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[6],
  );

  /// See [LocalWordEntity.ipa].
  static final ipa = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[7],
  );

  /// See [LocalWordEntity.vietnamesePronunciation].
  static final vietnamesePronunciation =
      obx.QueryStringProperty<LocalWordEntity>(_entities[2].properties[8]);

  /// See [LocalWordEntity.example].
  static final example = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[9],
  );

  /// See [LocalWordEntity.exampleVi].
  static final exampleVi = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[10],
  );

  /// See [LocalWordEntity.difficulty].
  static final difficulty = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[11],
  );

  /// See [LocalWordEntity.topicsJson].
  static final topicsJson = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[12],
  );

  /// See [LocalWordEntity.status].
  static final status = obx.QueryStringProperty<LocalWordEntity>(
    _entities[2].properties[13],
  );

  /// See [LocalWordEntity.lastSeenAtMs].
  static final lastSeenAtMs = obx.QueryIntegerProperty<LocalWordEntity>(
    _entities[2].properties[14],
  );

  /// See [LocalWordEntity.nextReviewAtMs].
  static final nextReviewAtMs = obx.QueryIntegerProperty<LocalWordEntity>(
    _entities[2].properties[15],
  );

  /// See [LocalWordEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<LocalWordEntity>(
    _entities[2].properties[16],
  );

  /// See [LocalWordEntity.updatedAtMs].
  static final updatedAtMs = obx.QueryIntegerProperty<LocalWordEntity>(
    _entities[2].properties[17],
  );
}

/// [StudyEventEntity] entity fields to define ObjectBox queries.
class StudyEventEntity_ {
  /// See [StudyEventEntity.id].
  static final id = obx.QueryIntegerProperty<StudyEventEntity>(
    _entities[3].properties[0],
  );

  /// See [StudyEventEntity.clientEventId].
  static final clientEventId = obx.QueryStringProperty<StudyEventEntity>(
    _entities[3].properties[1],
  );

  /// See [StudyEventEntity.localWordId].
  static final localWordId = obx.QueryStringProperty<StudyEventEntity>(
    _entities[3].properties[2],
  );

  /// See [StudyEventEntity.serverWordId].
  static final serverWordId = obx.QueryStringProperty<StudyEventEntity>(
    _entities[3].properties[3],
  );

  /// See [StudyEventEntity.rating].
  static final rating = obx.QueryStringProperty<StudyEventEntity>(
    _entities[3].properties[4],
  );

  /// See [StudyEventEntity.occurredAtMs].
  static final occurredAtMs = obx.QueryIntegerProperty<StudyEventEntity>(
    _entities[3].properties[5],
  );

  /// See [StudyEventEntity.syncStatus].
  static final syncStatus = obx.QueryStringProperty<StudyEventEntity>(
    _entities[3].properties[6],
  );
}

/// [SyncQueueEntity] entity fields to define ObjectBox queries.
class SyncQueueEntity_ {
  /// See [SyncQueueEntity.id].
  static final id = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[4].properties[0],
  );

  /// See [SyncQueueEntity.type].
  static final type = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[4].properties[1],
  );

  /// See [SyncQueueEntity.payload].
  static final payload = obx.QueryStringProperty<SyncQueueEntity>(
    _entities[4].properties[2],
  );

  /// See [SyncQueueEntity.retryCount].
  static final retryCount = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[4].properties[3],
  );

  /// See [SyncQueueEntity.nextRetryAtMs].
  static final nextRetryAtMs = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[4].properties[4],
  );

  /// See [SyncQueueEntity.createdAtMs].
  static final createdAtMs = obx.QueryIntegerProperty<SyncQueueEntity>(
    _entities[4].properties[5],
  );
}

/// [SpeakingAttemptEntity] entity fields to define ObjectBox queries.
class SpeakingAttemptEntity_ {
  /// See [SpeakingAttemptEntity.id].
  static final id = obx.QueryIntegerProperty<SpeakingAttemptEntity>(
    _entities[5].properties[0],
  );

  /// See [SpeakingAttemptEntity.attemptId].
  static final attemptId = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[1],
  );

  /// See [SpeakingAttemptEntity.promptId].
  static final promptId = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[2],
  );

  /// See [SpeakingAttemptEntity.serverWordId].
  static final serverWordId = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[3],
  );

  /// See [SpeakingAttemptEntity.occurredAtMs].
  static final occurredAtMs = obx.QueryIntegerProperty<SpeakingAttemptEntity>(
    _entities[5].properties[4],
  );

  /// See [SpeakingAttemptEntity.durationMs].
  static final durationMs = obx.QueryIntegerProperty<SpeakingAttemptEntity>(
    _entities[5].properties[5],
  );

  /// See [SpeakingAttemptEntity.retryCount].
  static final retryCount = obx.QueryIntegerProperty<SpeakingAttemptEntity>(
    _entities[5].properties[6],
  );

  /// See [SpeakingAttemptEntity.selfRating].
  static final selfRating = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[7],
  );

  /// See [SpeakingAttemptEntity.syncStatus].
  static final syncStatus = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[8],
  );

  /// See [SpeakingAttemptEntity.localAudioPath].
  static final localAudioPath = obx.QueryStringProperty<SpeakingAttemptEntity>(
    _entities[5].properties[9],
  );
}

/// [SpeakingPromptEntity] entity fields to define ObjectBox queries.
class SpeakingPromptEntity_ {
  /// See [SpeakingPromptEntity.id].
  static final id = obx.QueryIntegerProperty<SpeakingPromptEntity>(
    _entities[6].properties[0],
  );

  /// See [SpeakingPromptEntity.promptId].
  static final promptId = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[1],
  );

  /// See [SpeakingPromptEntity.wordSenseId].
  static final wordSenseId = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[2],
  );

  /// See [SpeakingPromptEntity.serverWordId].
  static final serverWordId = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[3],
  );

  /// See [SpeakingPromptEntity.targetText].
  static final targetText = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[4],
  );

  /// See [SpeakingPromptEntity.viHint].
  static final viHint = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[5],
  );

  /// See [SpeakingPromptEntity.targetPhrase].
  static final targetPhrase = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[6],
  );

  /// See [SpeakingPromptEntity.pronunciationTip].
  static final pronunciationTip = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[7],
  );

  /// See [SpeakingPromptEntity.commonMistake].
  static final commonMistake = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[8],
  );

  /// See [SpeakingPromptEntity.difficulty].
  static final difficulty = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[9],
  );

  /// See [SpeakingPromptEntity.topic].
  static final topic = obx.QueryStringProperty<SpeakingPromptEntity>(
    _entities[6].properties[10],
  );

  /// See [SpeakingPromptEntity.cachedAtMs].
  static final cachedAtMs = obx.QueryIntegerProperty<SpeakingPromptEntity>(
    _entities[6].properties[11],
  );
}
